######################################################################
###         DO NOT EXPOSE THIS FILE PUBLICLY AFTER EDITING         ###
######################################################################

claude_system: |
  # ここにシステム指示を書く。

  **マークダウンが利用可能です＊*

  - 詳細な内容

gpt_system: |
  # ここにシステム指示を書く。

  **マークダウンが利用可能です＊*

  - 詳細な内容
